import turtle as t


def scenery(n):
    # speed of the turtle
    t.speed(0)

    # for creating base of house 1
    t.fillcolor('yellow')
    t.begin_fill()
    t.right(90)
    t.forward(n / 2)
    t.left(90)
    t.forward(n)
    t.left(90)
    t.forward(n / 2)
    t.left(90)
    t.forward(n)
    t.right(90)
    t.end_fill()

    # for the triangle roof
    t.fillcolor('black')
    t.begin_fill()
    t.right(45)
    t.forward(213)
    t.right(90)
    t.forward(212)
    t.end_fill()

    # making the windows and door on house 1
    t.home()
    t.penup()
    t.goto(250,- 60)
    t.pendown()
    t.fillcolor('blue')
    t.begin_fill()
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.end_fill()
    t.penup()
    t.goto(60, - 60)
    t.pendown()
    t.fillcolor('blue')
    t.begin_fill()
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.end_fill()
    t.penup()
    t.forward(90)
    t.pendown()
    t.fillcolor('brown')
    t.begin_fill()
    t.right(90)
    t.forward(90)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(90)
    t.right(90)
    t.forward(50)
    t.end_fill()
    t.penup()

    t.home()

    t.goto(-450, 0)
    t.pendown()

    t.right(90)
    t.fillcolor('pink')
    t.begin_fill()

    # for creating base of house 2
    t.forward(n / 2)
    t.left(90)
    t.forward(n)
    t.left(90)
    t.forward(n / 2)
    t.left(90)
    t.forward(n)
    t.right(90)
    t.end_fill()

    # for the triangle roof
    t.fillcolor('grey')
    t.begin_fill()
    t.right(45)
    t.forward(213)
    t.right(90)
    t.forward(212)
    t.end_fill()

    # windows and door on house 2
    t.left(45)
    t.penup()
    t.goto(-200, - 60)
    t.pendown()
    t.fillcolor('blue')
    t.begin_fill()
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.end_fill()
    t.penup()
    t.goto(-390, - 60)
    t.pendown()
    t.fillcolor('blue')
    t.begin_fill()
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.right(90)
    t.forward(40)
    t.end_fill()
    t.penup()
    t.forward(90)
    t.pendown()
    t.fillcolor('brown')
    t.begin_fill()
    t.right(90)
    t.forward(90)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(90)
    t.right(90)
    t.forward(50)
    t.end_fill()
    t.penup()

    t.penup()
    t.goto(400, 0)
    t.pendown()

    # draw tree
    t.fillcolor('brown')
    t.begin_fill()
    t.right(90)
    t.forward(150)
    t.right(90)
    t.forward(25)
    t.right(90)
    t.forward(300)
    t.right(90)
    t.forward(25)
    t.right(90)
    t.forward(150)
    t.end_fill()
    t.left(180)
    t.forward(135)
    t.right(75)
    t.fillcolor('green')
    t.begin_fill()
    t.circle(60)
    t.end_fill()
    t.penup()
    t.home()
    t.mainloop()


scenery(300)
